
--------------------begin------------------------

[2019/12/26 09:29:43.92174][i][2fa5e3a18] recv loop terminated: err=failed to read from connection: read tcp 192.168.5.62:33722->192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:43.92182][i][2fa5e3a18] send loop terminated: err=<nil>
[2019/12/26 09:29:43.92218][w][2fa5e3a18] zk已断开连接:[192.168.0.101]
[2019/12/26 09:29:45.92481][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:47.92718][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:49.93408][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:51.94187][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:53.94631][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:55.95052][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:57.95401][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:29:59.95727][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:01.96221][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:03.96625][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:05.97052][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:07.98735][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:09.99106][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:11.99621][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:13.100316][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 09:30:14.441439][i][2fa5e3a18] Connected to 192.168.0.101:2181
[2019/12/26 09:30:14.462140][i][2fa5e3a18] authentication failed: zk: session has been expired by the server
[2019/12/26 09:30:14.462218][w][2fa5e3a18] zk已断开连接:[192.168.0.101]
[2019/12/26 09:30:17.371820][i][2fa5e3a18] Connected to 192.168.0.101:2181
[2019/12/26 09:30:17.393449][i][2fa5e3a18] authenticated: id=103116747297987064, timeout=4000
[2019/12/26 09:30:17.393464][i][2fa5e3a18] re-submitting `0` credentials after reconnect
[2019/12/26 09:30:18.399907][i][051ef75e9] 开始启动[API]服务...
[2019/12/26 09:30:18.400268][e][051ef75e9] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------

--------------------begin------------------------

[2019/12/26 12:36:37.838768][i][2fa5e3a18] recv loop terminated: err=failed to read from connection: read tcp 192.168.5.62:49628->192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:37.838791][i][2fa5e3a18] send loop terminated: err=<nil>
[2019/12/26 12:36:37.838920][w][2fa5e3a18] zk已断开连接:[192.168.0.101]
[2019/12/26 12:36:39.839383][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:41.839928][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:43.840151][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:45.840443][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:47.840913][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:49.841290][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:51.841708][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:53.842129][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:55.842509][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:57.842882][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:36:59.843320][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:37:01.843685][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:37:03.79568][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2019/12/26 12:37:05.80141][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:37:06.123416][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2019/12/26 12:37:08.123690][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: i/o timeout
[2019/12/26 12:37:09.198530][i][2fa5e3a18] Failed to connect to 192.168.0.101:2181: dial tcp 192.168.0.101:2181: connect: no route to host
[2019/12/26 12:37:10.199061][i][2fa5e3a18] Connected to 192.168.0.101:2181
[2019/12/26 12:37:10.201058][i][2fa5e3a18] authentication failed: zk: session has been expired by the server
[2019/12/26 12:37:10.201110][w][2fa5e3a18] zk已断开连接:[192.168.0.101]
[2019/12/26 12:37:11.202144][i][2fa5e3a18] Connected to 192.168.0.101:2181
[2019/12/26 12:37:11.222969][i][2fa5e3a18] authenticated: id=103116747297987154, timeout=4000
[2019/12/26 12:37:11.222985][i][2fa5e3a18] re-submitting `0` credentials after reconnect
[2019/12/26 12:37:12.249676][i][7ce8487ce] 开始启动[API]服务...
[2019/12/26 12:37:12.249780][e][7ce8487ce] 启动失败 创建db失败:{
  "provider": "mysql",
  "connString": "oms_t:123456@tcp(192.168.0.36)/oms_t?charset=utf8",
  "maxOpen": 20,
  "maxIdle": 10,
  "lifeTime": 600
},err:sql: unknown driver "mysql" (forgotten import?)

---------------------end-------------------------
